
model: htdemucs  # see demucs/train.py for the possibilities, and config for each model hereafter.


dset:
  wav: '/dset_vol'
  samplerate: 48000
  use_musdb: false   # set to false to not use musdb as training data.
  channels: 2
  segment: 11
  sources: ['Kick','Snare','Toms','Cymbals']

epochs: 120
batch_size: 8

dora:
  dir: '/outputs'

augment:
  shift_same: false
  scale:
    proba: 0
  remix:
    proba: 0
  repitch:
    proba: 0