
model: htdemucs  # see demucs/train.py for the possibilities, and config for each model hereafter.


dset:
  wav: "/rmk-tiny-test-dset"
  samplerate: 48000
  use_musdb: false   # set to false to not use musdb as training data.
  channels: 2
  segment: 11
  sources: ['kick','snare','toms','cymbals']
  epochs: 120
  batch_size: 64

dora:
  dir: "/outputs"

augment:
  shift_same: false
  scale:
    proba: 0
  remix:
    proba: 0
  repitch:
    proba: 0